import {performance} from "node:perf_hooks";
import pg from "pg";
import mysql from "mysql2/promise";
import sql from "mssql";
import {MongoClient} from "mongodb";

export type DatabaseEngine="POSTGRESQL"|"MYSQL"|"SQLSERVER"|"MONGODB";
export type DatabaseMetrics={connectionsUsed:number|null;connectionsMax:number|null;databaseSizeBytes:number|null;replicationLagSeconds:number|null;longRunningQueries:number|null;details:Record<string,unknown>};
export type DatabaseProbe={responseTimeMs:number;message:string;metrics:DatabaseMetrics};
const empty=():DatabaseMetrics=>({connectionsUsed:null,connectionsMax:null,databaseSizeBytes:null,replicationLagSeconds:null,longRunningQueries:null,details:{}});
const numberOrNull=(value:unknown)=>value===null||value===undefined||!Number.isFinite(Number(value))?null:Number(value);

async function postgres(connectionString:string,timeoutSeconds:number):Promise<DatabaseProbe>{
  const started=performance.now(),client=new pg.Client({connectionString,connectionTimeoutMillis:timeoutSeconds*1000,query_timeout:timeoutSeconds*1000,statement_timeout:timeoutSeconds*1000,application_name:"Byakugan"});
  try{await client.connect();const ping=await client.query("SELECT current_database() database, current_setting('server_version') version");const [connections,size,replication,longRunning]=await Promise.allSettled([client.query("SELECT count(*)::int used, current_setting('max_connections')::int max FROM pg_stat_activity"),client.query("SELECT pg_database_size(current_database())::bigint bytes"),client.query("SELECT COALESCE(max(EXTRACT(EPOCH FROM replay_lag)),0) lag FROM pg_stat_replication"),client.query("SELECT count(*)::int count FROM pg_stat_activity WHERE state <> 'idle' AND pid <> pg_backend_pid() AND query_start < now()-interval '30 seconds'")]);const value=(result:PromiseSettledResult<pg.QueryResult>,key:string)=>result.status==="fulfilled"?result.value.rows[0]?.[key]:null;return{responseTimeMs:Math.round(performance.now()-started),message:`PostgreSQL ${ping.rows[0].version} · ${ping.rows[0].database}`,metrics:{connectionsUsed:numberOrNull(value(connections,"used")),connectionsMax:numberOrNull(value(connections,"max")),databaseSizeBytes:numberOrNull(value(size,"bytes")),replicationLagSeconds:numberOrNull(value(replication,"lag")),longRunningQueries:numberOrNull(value(longRunning,"count")),details:{database:ping.rows[0].database,version:ping.rows[0].version}}}}finally{await client.end().catch(()=>undefined)}}

async function mySql(connectionString:string,timeoutSeconds:number):Promise<DatabaseProbe>{
  const started=performance.now(),connection=await mysql.createConnection({...({uri:connectionString} as any),connectTimeout:timeoutSeconds*1000});
  try{const [[info]]:any=await connection.query("SELECT DATABASE() database_name, VERSION() version");const results=await Promise.allSettled([connection.query("SELECT COUNT(*) used FROM information_schema.processlist"),connection.query("SELECT @@max_connections max_connections"),connection.query("SELECT COALESCE(SUM(data_length+index_length),0) bytes FROM information_schema.tables WHERE table_schema=DATABASE()"),connection.query("SELECT COUNT(*) count FROM information_schema.processlist WHERE COMMAND <> 'Sleep' AND TIME > 30")]);const row=(index:number)=>results[index].status==="fulfilled"?(results[index] as PromiseFulfilledResult<any>).value[0][0]:{};return{responseTimeMs:Math.round(performance.now()-started),message:`MySQL/MariaDB ${info.version} · ${info.database_name??"server"}`,metrics:{connectionsUsed:numberOrNull(row(0).used),connectionsMax:numberOrNull(row(1).max_connections),databaseSizeBytes:numberOrNull(row(2).bytes),replicationLagSeconds:null,longRunningQueries:numberOrNull(row(3).count),details:{database:info.database_name,version:info.version}}}}finally{await connection.end().catch(()=>undefined)}}

async function sqlServer(connectionString:string,timeoutSeconds:number):Promise<DatabaseProbe>{
  const started=performance.now(),pool=new sql.ConnectionPool(connectionString);void timeoutSeconds;
  try{await pool.connect();const info=await pool.request().query("SELECT DB_NAME() database_name, CAST(SERVERPROPERTY('ProductVersion') AS nvarchar(100)) version");const results=await Promise.allSettled([pool.request().query("SELECT COUNT(*) used FROM sys.dm_exec_sessions WHERE is_user_process=1"),pool.request().query("SELECT CAST(value_in_use AS int) max_connections FROM sys.configurations WHERE name='user connections'"),pool.request().query("SELECT SUM(CAST(size AS bigint))*8192 bytes FROM sys.database_files"),pool.request().query("SELECT COUNT(*) count FROM sys.dm_exec_requests WHERE session_id<>@@SPID AND total_elapsed_time>30000")]);const row=(index:number)=>results[index].status==="fulfilled"?(results[index] as PromiseFulfilledResult<sql.IResult<any>>).value.recordset[0]??{}:{};const max=numberOrNull(row(1).max_connections);return{responseTimeMs:Math.round(performance.now()-started),message:`SQL Server ${info.recordset[0].version} · ${info.recordset[0].database_name}`,metrics:{connectionsUsed:numberOrNull(row(0).used),connectionsMax:max===0?32767:max,databaseSizeBytes:numberOrNull(row(2).bytes),replicationLagSeconds:null,longRunningQueries:numberOrNull(row(3).count),details:{database:info.recordset[0].database_name,version:info.recordset[0].version}}}}finally{await pool.close().catch(()=>undefined)}}

async function mongo(connectionString:string,timeoutSeconds:number):Promise<DatabaseProbe>{
  const started=performance.now(),client=new MongoClient(connectionString,{connectTimeoutMS:timeoutSeconds*1000,serverSelectionTimeoutMS:timeoutSeconds*1000});
  try{await client.connect();const database=client.db(),ping=await database.command({ping:1});if(ping.ok!==1)throw new Error("MongoDB ping failed");const [server,stats,current]=await Promise.allSettled([database.admin().serverStatus(),database.stats(),database.admin().command({currentOp:1,$all:true,secs_running:{$gte:30}})]);const serverValue=server.status==="fulfilled"?server.value:{} as any,statsValue=stats.status==="fulfilled"?stats.value:{} as any,currentValue=current.status==="fulfilled"?current.value:{} as any;return{responseTimeMs:Math.round(performance.now()-started),message:`MongoDB ${serverValue.version??"connected"} · ${database.databaseName}`,metrics:{connectionsUsed:numberOrNull(serverValue.connections?.current),connectionsMax:numberOrNull(serverValue.connections?.available===undefined?null:Number(serverValue.connections.current)+Number(serverValue.connections.available)),databaseSizeBytes:numberOrNull(statsValue.dataSize),replicationLagSeconds:null,longRunningQueries:numberOrNull(currentValue.inprog?.length),details:{database:database.databaseName,version:serverValue.version??null}}}}finally{await client.close().catch(()=>undefined)}}

export async function probeDatabase(engine:DatabaseEngine,connectionString:string,timeoutSeconds:number){if(engine==="POSTGRESQL")return postgres(connectionString,timeoutSeconds);if(engine==="MYSQL")return mySql(connectionString,timeoutSeconds);if(engine==="SQLSERVER")return sqlServer(connectionString,timeoutSeconds);return mongo(connectionString,timeoutSeconds)}
