import nodemailer from "nodemailer";
import {GetObjectLockConfigurationCommand,HeadBucketCommand,PutObjectCommand,S3Client} from "@aws-sdk/client-s3";

export type SmtpConfig={host:string;port:number;secure:boolean;username?:string;password?:string;from:string;recipients:string[]};
export type S3Config={endpoint?:string;region:string;bucket:string;prefix:string;accessKeyId:string;secretAccessKey:string;forcePathStyle:boolean;wormMode?:"NONE"|"GOVERNANCE"|"COMPLIANCE";retentionDays?:number;legalHold?:boolean};
export type DeliveryConfig={type:"SMTP";config:SmtpConfig}|{type:"S3";config:S3Config};

function smtp(config:SmtpConfig){return nodemailer.createTransport({host:config.host,port:config.port,secure:config.secure,auth:config.username?{user:config.username,pass:config.password}:undefined,connectionTimeout:15_000,greetingTimeout:15_000,socketTimeout:30_000,tls:{minVersion:"TLSv1.2"}})}
function s3(config:S3Config){return new S3Client({region:config.region,endpoint:config.endpoint||undefined,forcePathStyle:config.forcePathStyle,credentials:{accessKeyId:config.accessKeyId,secretAccessKey:config.secretAccessKey},requestChecksumCalculation:"WHEN_REQUIRED",responseChecksumValidation:"WHEN_REQUIRED"})}
const cleanPrefix=(value:string)=>value.replace(/^\/+|\/+$/g,"");

export function deliveryDestination(value:DeliveryConfig){return value.type==="SMTP"?value.config.recipients.join(", "):`s3://${value.config.bucket}/${cleanPrefix(value.config.prefix)}`.replace(/\/$/,"")}

export async function testDeliveryChannel(value:DeliveryConfig){if(value.type==="SMTP"){const transport=smtp(value.config);await transport.verify();return{destination:deliveryDestination(value),wormEnabled:false}}const client=s3(value.config);try{await client.send(new HeadBucketCommand({Bucket:value.config.bucket}));const worm=(value.config.wormMode??"NONE")!=="NONE"||Boolean(value.config.legalHold);if(worm){const lock=await client.send(new GetObjectLockConfigurationCommand({Bucket:value.config.bucket}));if(lock.ObjectLockConfiguration?.ObjectLockEnabled!=="Enabled")throw Object.assign(new Error("Object Lock is not enabled on this bucket"),{code:"OBJECT_LOCK_NOT_ENABLED"})}return{destination:deliveryDestination(value),wormEnabled:worm}}finally{client.destroy()}}

export async function deliverReport(value:DeliveryConfig,input:{buffer:Buffer;fileName:string;format:string;sha256:string;scheduleName:string;period:{from:string;to:string}}){if(value.type==="SMTP"){const transport=smtp(value.config);const info=await transport.sendMail({from:value.config.from,to:value.config.recipients,subject:`Byakugan audit evidence · ${input.scheduleName}`,text:`Automated audit evidence report\nPeriod: ${input.period.from} to ${input.period.to}\nSHA-256: ${input.sha256}\n\nGenerated automatically by Byakugan.`,attachments:[{filename:input.fileName,content:input.buffer,contentType:input.format==="PDF"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}]});return{destination:deliveryDestination(value),objectKey:info.messageId}}
  const prefix=cleanPrefix(value.config.prefix),key=[prefix,input.period.to.slice(0,10),input.fileName].filter(Boolean).join("/"),mode=value.config.wormMode??"NONE",retainUntil=mode!=="NONE"?new Date(Date.now()+(value.config.retentionDays??365)*86400000):undefined;const client=s3(value.config);try{const result=await client.send(new PutObjectCommand({Bucket:value.config.bucket,Key:key,Body:input.buffer,ContentType:input.format==="PDF"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",Metadata:{sha256:input.sha256,"supapulse-schedule":input.scheduleName.slice(0,100),...(mode!=="NONE"?{"worm-mode":mode,"retain-until":retainUntil!.toISOString()}: {})},ObjectLockMode:mode==="NONE"?undefined:mode,ObjectLockRetainUntilDate:retainUntil,ObjectLockLegalHoldStatus:value.config.legalHold?"ON":undefined}));return{destination:deliveryDestination(value),objectKey:key,wormMode:mode,retainUntil:retainUntil?.toISOString()??null,legalHold:Boolean(value.config.legalHold),objectVersionId:result.VersionId??null,immutableVerified:mode!=="NONE"||Boolean(value.config.legalHold)}}finally{client.destroy()}}

export function deliveryErrorCode(error:unknown){const raw=typeof error==="object"&&error?("code" in error?(error as {code:unknown}).code:"name" in error?(error as {name:unknown}).name:null):null;return String(raw??"DELIVERY_FAILED").replace(/[^A-Z0-9_-]/gi,"").slice(0,80)||"DELIVERY_FAILED"}
