import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import PDFDocument from "pdfkit";
import archiver = require("archiver");
import { db } from "./database.js";
import { verifyAuditChain } from "./audit.js";

type Row=Record<string,unknown>;
export type ReportLocale="en-US"|"th-TH";
const copy={"en-US":{title:"Byakugan Audit Report",period:"Period",generated:"Generated",chain:"Evidence chain",summary:"Executive summary",none:"No evidence in selected period.",findings:"Compliance findings",vulnerabilities:"Vulnerabilities",backups:"Backup evidence",restores:"Restore tests",sheets:["Summary","Assets","Findings","Vulnerabilities","Backups","Restore Tests","Incidents"]},"th-TH":{title:"รายงานออดิต Byakugan",period:"ช่วงเวลา",generated:"สร้างเมื่อ",chain:"ห่วงโซ่หลักฐาน",summary:"สรุปสำหรับผู้บริหาร",none:"ไม่พบหลักฐานในช่วงเวลาที่เลือก",findings:"รายการด้านการกำกับดูแล",vulnerabilities:"ช่องโหว่",backups:"หลักฐานการสำรองข้อมูล",restores:"การทดสอบกู้คืน",sheets:["สรุป","สินทรัพย์","รายการตรวจพบ","ช่องโหว่","ข้อมูลสำรอง","ทดสอบกู้คืน","เหตุการณ์"]}} as const;
function thaiFont(){return ["/usr/share/fonts/truetype/noto/NotoSansThai-Regular.ttf","C:/Windows/Fonts/LeelawUI.ttf"].find(existsSync)}
export function auditPeriod(fromValue?:string,toValue?:string){const to=toValue?new Date(toValue):new Date();const from=fromValue?new Date(fromValue):new Date(to.getTime()-90*86400000);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||from>to)throw new Error("Invalid date range");return{from:from.toISOString(),to:to.toISOString()}}
export function collectAuditReport(from:string,to:string){
  const assets=db.prepare(`SELECT name,monitor_type AS type,asset_tag AS assetTag,asset_owner AS owner,environment,criticality,last_status AS status,last_checked_at AS lastCheckedAt FROM projects ORDER BY name`).all() as Row[];
  const findings=db.prepare(`SELECT f.severity,f.status,f.category,f.title,a.hostname,f.owner,f.due_at AS dueAt,f.first_detected_at AS firstDetectedAt,f.resolved_at AS resolvedAt FROM compliance_findings f LEFT JOIN agents a ON a.id=f.agent_id WHERE f.first_detected_at<=? AND(f.resolved_at IS NULL OR f.resolved_at>=?) ORDER BY f.severity`).all(to,from) as Row[];
  const vulnerabilities=db.prepare(`SELECT v.severity,v.status,v.vulnerability_id AS cve,v.package_name AS package,v.installed_version AS installedVersion,v.fixed_version AS fixedVersion,a.hostname,v.owner,v.due_at AS dueAt,v.risk_reason AS riskReason,CASE v.kev WHEN 1 THEN 'YES' ELSE 'NO' END AS knownExploited,v.kev_due_date AS cisaDueDate,v.kev_ransomware AS ransomwareUse,v.epss_score AS epssProbability,v.epss_percentile AS epssPercentile,v.threat_intel_updated_at AS intelligenceUpdatedAt FROM vulnerability_findings v JOIN agents a ON a.id=v.agent_id WHERE v.first_detected_at<=? AND(v.resolved_at IS NULL OR v.resolved_at>=?) ORDER BY v.kev DESC,COALESCE(v.epss_score,0) DESC,v.severity`).all(to,from) as Row[];
  const backups=db.prepare(`SELECT asset_name AS asset,backup_type AS type,storage_location AS location,status,started_at AS startedAt,completed_at AS completedAt,size_bytes AS sizeBytes,checksum FROM backup_evidence WHERE started_at BETWEEN ? AND ? ORDER BY started_at`).all(from,to) as Row[];
  const restores=db.prepare(`SELECT asset_name AS asset,test_scope AS scope,result,tested_at AS testedAt,rto_minutes AS rtoMinutes,actual_minutes AS actualMinutes,evidence_note AS evidenceNote FROM restore_tests WHERE tested_at BETWEEN ? AND ? ORDER BY tested_at`).all(from,to) as Row[];
  const incidents=db.prepare(`SELECT p.name AS asset,i.status,i.severity,i.owner,i.message,i.root_cause AS rootCause,i.corrective_action AS correctiveAction,i.lessons_learned AS lessonsLearned,i.review_status AS reviewStatus,i.started_at AS startedAt,i.resolved_at AS resolvedAt FROM incidents i JOIN projects p ON p.id=i.project_id WHERE i.started_at BETWEEN ? AND ? ORDER BY i.started_at`).all(from,to) as Row[];
  const count=(rows:Row[],key:string,value:string)=>rows.filter(row=>row[key]===value).length;
  return{period:{from,to},generatedAt:new Date().toISOString(),auditChain:verifyAuditChain(),summary:{assets:assets.length,openFindings:findings.filter(x=>x.status!=="RESOLVED").length,criticalVulnerabilities:count(vulnerabilities,"severity","CRITICAL"),backups:backups.length,failedBackups:count(backups,"status","FAILED"),restoreTests:restores.length,passedRestores:count(restores,"result","PASS"),incidents:incidents.length},assets,findings,vulnerabilities,backups,restores,incidents};
}
function text(value:unknown){return String(value??"")}
export async function createPdfReport(data:ReturnType<typeof collectAuditReport>,locale:ReportLocale="en-US",timezone="UTC"){return await new Promise<Buffer>((resolve,reject)=>{const words=copy[locale],doc=new PDFDocument({size:"A4",margin:46,info:{Title:`${words.title} - ISO 27001`,Author:"Byakugan",Subject:`Locale=${locale}; Timezone=${timezone}; UTC=${data.generatedAt}`}});const font=locale==="th-TH"?thaiFont():undefined;if(font)doc.font(font);const chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);
  const local=(value:string)=>new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"long",timeZone:timezone}).format(new Date(value));doc.fillColor("#123047").fontSize(24).text(words.title);doc.moveDown(.3).fillColor("#4b6478").fontSize(10).text(`${words.period}: ${local(data.period.from)} — ${local(data.period.to)}`).text(`${words.generated}: ${local(data.generatedAt)} (${timezone})`).text(`UTC: ${data.generatedAt}`).text(`${words.chain}: ${data.auditChain.valid?"VALID":"FAILED"} (${data.auditChain.events})`);doc.moveDown();
  doc.fillColor("#123047").fontSize(15).text(words.summary);doc.moveDown(.4);for(const [label,value] of Object.entries(data.summary)){doc.fillColor("#334e62").fontSize(10).text(`${label.replace(/([A-Z])/g," $1")}: ${value}`)}
  const section=(title:string,rows:Row[],columns:string[])=>{doc.addPage();if(font)doc.font(font);doc.fillColor("#123047").fontSize(16).text(title);doc.moveDown(.5);if(!rows.length){doc.fillColor("#718096").fontSize(10).text(words.none);return}for(const row of rows.slice(0,250)){if(doc.y>750){doc.addPage();if(font)doc.font(font)}doc.fillColor("#1f3344").fontSize(9).text(columns.map(key=>`${key}: ${text(row[key])}`).join("  |  "),{width:500});doc.moveDown(.25)}};
  section(words.findings,data.findings,["severity","status","title","hostname","owner","dueAt"]);section(words.vulnerabilities,data.vulnerabilities,["severity","status","cve","package","hostname","fixedVersion"]);section(words.backups,data.backups,["asset","type","status","startedAt","location"]);section(words.restores,data.restores,["asset","result","testedAt","rtoMinutes","actualMinutes"]);
  doc.end()})}
function xml(value:unknown){return text(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function colName(index:number){let result="";for(let value=index+1;value;value=Math.floor((value-1)/26))result=String.fromCharCode(65+(value-1)%26)+result;return result}
function sheetXml(rows:Row[]){const columns=rows.length?Object.keys(rows[0]):["No evidence"];const all=[Object.fromEntries(columns.map(key=>[key,key])),...rows];return`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${all.map((row,r)=>`<row r="${r+1}">${columns.map((key,c)=>`<c r="${colName(c)}${r+1}" t="inlineStr"${r===0?' s="1"':''}><is><t>${xml(row[key])}</t></is></c>`).join("")}</row>`).join("")}</sheetData><autoFilter ref="A1:${colName(columns.length-1)}${Math.max(all.length,1)}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews></worksheet>`}
export async function createXlsxReport(data:ReturnType<typeof collectAuditReport>,locale:ReportLocale="en-US",timezone="UTC"){const names=copy[locale].sheets,summary=[{metric:"locale",value:locale},{metric:"timezone",value:timezone},{metric:"generatedAtUtc",value:data.generatedAt},...Object.entries(data.summary).map(([metric,value])=>({metric,value}))];const sheets=[{name:names[0],rows:summary},{name:names[1],rows:data.assets},{name:names[2],rows:data.findings},{name:names[3],rows:data.vulnerabilities},{name:names[4],rows:data.backups},{name:names[5],rows:data.restores},{name:names[6],rows:data.incidents}];const archive=new archiver.ZipArchive({zlib:{level:9}});const chunks:Buffer[]=[];archive.on("data",chunk=>chunks.push(Buffer.from(chunk)));const done=new Promise<Buffer>((resolve,reject)=>{archive.on("end",()=>resolve(Buffer.concat(chunks)));archive.on("error",reject)});
  archive.append(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`,{name:"[Content_Types].xml"});archive.append(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,{name:"_rels/.rels"});archive.append(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((sheet,i)=>`<sheet name="${xml(sheet.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`,{name:"xl/workbook.xml"});archive.append(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,{name:"xl/_rels/workbook.xml.rels"});archive.append(`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font/><font><b/><color rgb="FFFFFFFF"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF123047"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf/><xf fontId="1" fillId="1" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`,{name:"xl/styles.xml"});sheets.forEach((sheet,i)=>archive.append(sheetXml(sheet.rows),{name:`xl/worksheets/sheet${i+1}.xml`}));void archive.finalize();return await done}
export function reportSha256(buffer:Buffer){return createHash("sha256").update(buffer).digest("hex")}
